export const mockTiles = [
  {
    id: 1,
    name: "tile1",
    status: "inTradingDesk",
    active : false,
    size: { width: "300px", height: "100px" },
    position: { x: 100, y: 100 },
  },
  {
    id: 2,
    name: "tile2",
    status: "inTradingDesk",
    active : false,
    size: { width: "300px", height: "100px" },
    position: { x: 200, y: 200 },
  },
  {
    id: 3,
    name: "tile3",
    status: "inTradingDesk",
    active : false,
    size: { width: "300px", height: "100px" },
    position: { x: 300, y: 300 },
  },
  {
    id: 4,
    name: "tile4",
    status: "inTradingDesk",
    active : false,
    size: { width: "300px", height: "100px" },
    position: { x: 400, y:400 },
  },
  {
    id: 5,
    name: "tile5",
    status: "inTradingDesk",
    active : false,
    size: { width: "300px", height: "100px" },
    position: { x: 500, y: 500 },
  },
];
